spring.application.name=AlquilaTusVehiculos
spring.profiles.active=dev

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false

# Base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/alquiler_edoh
spring.datasource.username=root
spring.datasource.password=19978

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect